all:
  hosts:
    master-1:
      ansible_host: 89.169.130.10
      ip: 10.0.1.14
      access_ip: 10.0.1.14
      ansible_user: debian
    worker-1:
      ansible_host: 89.169.133.56
      ip: 10.0.1.12
      access_ip: 10.0.1.12
      ansible_user: debian
    worker-2:
      ansible_host: 89.169.147.227
      ip: 10.0.1.22
      access_ip: 10.0.1.22
      ansible_user: debian
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}